### ISSUE TITLE
There is error using with UUID

### ISSUE THREAD

**Issue by trippo** [kirschbaum-development/laravel-queue-batch-retry#1]
I tried but obtain 
SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: '385f48fa-b414-4008-befe-979ab21177fd' (SQL: delete from `failed_jobs` where `uuid` = 1)

**Comment by luisdalmolin** [comment]
failed_jobs with UUIDs are in fact not working when trying to re-run jobs, but the deletion should work. Your error message tells me you tried to use `artisan queue:retry` instead, with an ID instead of the UUID.

Either way, 1.1.0 is tagged with the fix.
